source "https://rubygems.org"

gem "jekyll"
gem 'rake'

group :test do
  gem 'html-proofer'
  gem 'rubocop'
  gem 'activesupport'
  gem 'stringex'
  gem 'colorator'
  gem 'colorize'
end


# If you have any plugins, put them here!
group :jekyll_plugins do
   gem 'jemoji'
   gem "jekyll-feed", "~> 0.6"
   gem 'bootstrap', '~> 4.0.0.alpha6'
   gem 'autoprefixer-rails'
   gem 'jekyll-assets'
   gem 'jekyll-archives'
   gem 'jekyll-last-modified-at'
   gem 'jekyll-plantuml'
   gem 'jekyll-mentions'
   gem 'jekyll-redirect-from'
   gem 'jekyll-sitemap'
   gem 'jekyll-paginate'
   gem 'jekyll-time-to-read'
   gem 'jekyll-watch'
#   gem 'jekyll-categories'
   gem 'jekyll-sass-converter'
   gem 'jekyll-coffeescript'
   gem 'jekyll-tidy'
   gem "minima", "~> 2.0"
   gem 'kramdown'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
